
tag: Trainer Mage
name: Mage Trainer
hostility: Never
affiliation: Adept Mage

items:
  equipment:
    rightHand: Antanian Staff
    armor: Antanian Tunic
    
behaviors:
  - type: trainer
    trainClass: [Mage]