
tag: Trainer Thief
name: Thief Trainer
hostility: Never
affiliation: Adept Thief

hp:
  min: 100000
  max: 100000

items:
  equipment:
    rightHand: Antanian Dagger
    armor: Antanian Studded Tunic
    
behaviors:
  - type: trainer
    trainClass: [Thief]
    joinClass: Thief