
tag: Trainer Mage
hostility: Never
affiliation: Adept Mage

hp:
  min: 1000000
  max: 1000000

mp:
  min: 100000
  max: 100000

level: 50

usableSkills:
  - MagicBolt

otherStats:
  int: 50

items:
  equipment:
    rightHand: Antanian Staff
    armor: Antanian Tunic
    
behaviors:
  - type: trainer
    trainClass: [Mage]
    joinClass: Mage
    props: ['maxLevelUpLevel', 'maxSkillTrain']