
tag: Trainer Thief
hostility: Never
affiliation: Master Thief

items:
  gear:
    rightHand: Antanian Longsword
    leftHand: Antanian Wooden Shield
    Armor: Antanian Breastplate
    
behaviors:
  - type: trainer