
tag: Trainer Traveller
hostility: Never
affiliation: Adept

hp:
  min: 1000000
  max: 1000000

mp:
  min: 100000
  max: 100000

level: 50

otherStats:
  str: 30
  wis: 30

usableSkills:
  - Afflict

items:
  equipment:
    rightHand: Antanian Shortbow
    armor: Antanian Breastplate
    
behaviors:
  - type: trainer
    trainClass: [Traveller]
    props: ['maxLevelUpLevel', 'maxSkillTrain']