
tag: Trainer Mage
hostility: Never
affiliation: Adept Mage

hp:
  min: 100000
  max: 100000

level: 50

usableSkills:
  - MagicBolt

items:
  equipment:
    rightHand: Antanian Staff
    armor: Antanian Tunic
    
behaviors:
  - type: trainer
    trainClass: [Mage]
    joinClass: Mage