
tag: Trainer Healer
hostility: Never
affiliation: Adept Healer

hp:
  min: 1000000
  max: 1000000

mp:
  min: 100000
  max: 100000

level: 50

usableSkills:
  - Afflict

otherStats:
  wis: 30

items:
  equipment:
    rightHand: Antanian Mace
    armor: Antanian Breastplate
    
behaviors:
  - type: trainer
    trainClass: [Healer]
    joinClass: Healer
    props: ['maxLevelUpLevel', 'maxSkillTrain']