
tag: Trainer Thief
hostility: Never
affiliation: Adept Thief

hp:
  min: 100000
  max: 100000

level: 50

items:
  equipment:
    rightHand: Antanian Returning Dagger
    armor: Antanian Studded Tunic
    
behaviors:
  - type: trainer
    trainClass: [Thief]
    joinClass: Thief
    props: ['maxLevelUpLevel', 'maxSkillTrain']