
tag: Trainer Warrior
name: Warrior Trainer
hostility: Never
affiliation: Adept Warrior

items:
  equipment:
    rightHand: Antanian Longsword
    leftHand: Antanian Wooden Shield
    armor: Antanian Breastplate
    
behaviors:
  - type: trainer
    trainClass: [Warrior]