
tag: Trainer Warrior
name: Warrior Trainer
hostility: Never
affiliation: Adept Warrior

hp:
  min: 100000
  max: 100000

level: 50

items:
  equipment:
    rightHand: Antanian Returning Longsword
    leftHand: Antanian Wooden Shield
    armor: Antanian Breastplate
    
behaviors:
  - type: trainer
    trainClass: [Warrior]
    joinClass: Warrior