
tag: Trainer Healer
name: Healer Trainer
hostility: Never
affiliation: Master Thief

items:
  equipment:
    rightHand: Antanian Mace
    armor: Antanian Breastplate
    
behaviors:
  - type: trainer