
tag: Trainer Warrior
name: Warrior Trainer
hostility: Never
affiliation: Master Thief

items:
  gear:
    rightHand: Antanian Longsword
    leftHand: Antanian Wooden Shield
    armor: Antanian Breastplate
    
behaviors:
  - type: trainer