
tag: Trainer Thief
name: Thief Trainer
hostility: Never
affiliation: Master Thief

items:
  equipment:
    rightHand: Antanian Dagger
    armor: Antanian Studded Tunic
    
behaviors:
  - type: trainer