

auth:
  verificationHourExpiration: 1

character:
  maxLevel: 50
  maxSkill: 30
  maxStats: 25
  chaSlidingDiscount: 7
  hpRegenSlidingCon: 21
  defaultMove: 3
  defaultCasterMPRegen: 10
  thiefOOCRegen: 10
  thiefICRegen: 1
  warriorOOCRegen: -3
  warriorICRegen: 3
  warriorHitRegen: 3
  warriorDodgeRegen: 5
  thiefStealthMultiplier: 1.5
  stealthEncumberDivisor: 2
  thiefLockpickFuzz: 2
  sellValuePercent: 25
  sellChaBaseBoost: 10
  sellChaBaseDivisor: 5
  fallDamagePercent: 15
  trainingCostGoldMultiplier: 25
  axpPerLevel: 500
  baseXP: 1000
  baseRep: 500

combat:
  buildUpDecay: 3
  buildUpStart: 5
  buildUpMax: 200
  buildUpScale: 10
  cstunConMultiplier: 21
  offhandDamageReduction: 0.8
  resourceConditionDamage: 50

corpse:
  playerExpire: 500
  npcExpire: 120
  rotStrLossChance: 5
  rotAgiLossChance: 5
  eatXpLossMultiplier: 0.01
  eatSkillLossMultiplier: 500

# 1/X chance for a common event to happen randomly
event:
  common: 10000
  uncommon: 15000
  rare: 25000
  legendary: 50000

ground:
  saveTicks: 150
  expireTicks: 1800

npcgen:
  attrMult: 2
  eliteMult: 4
  levelFuzz: 2
  eliteLootMult: 2
  normalLootMult: 1

  potionDrops:
    Antania:
      Antanian Strength Potion: 100
      Antanian Agility Potion: 100
      Antanian Dexterity Potion: 50
      Antanian Intelligence Potion: 100
      Antanian Wisdom Potion: 100
      Antanian Willpower Potion: 250
      Antanian Luck Potion: 500
      Antanian Charisma Potion: 400

    Risan:
      Risan Strength Potion: 150
      Risan Agility Potion: 150
      Risan Dexterity Potion: 100
      Risan Intelligence Potion: 150
      Risan Wisdom Potion: 150
      Risan Willpower Potion: 350
      Risan Luck Potion: 700
      Risan Charisma Potion: 550

npcscript:
  trainer:
    assessCost: 50
    trainCost: 200
    resetCost: 10000

  steelrose:
    maxListings: 25

  hpdoc:
    levels:       [0, 13, 25, 50]
    normalizers:  [100, 200, 300, 1500]
    costs:
      - { min: 100,     max: 500 }
      - { min: 5000,    max: 15000 }
      - { min: 100000,  max: 1000000 }
      - { min: 1000000, max: 10000000 }
    values:
      Mage:       [100, 375, 600, 2400]
      Thief:      [100, 425, 700, 2800]
      Healer:     [100, 400, 650, 2600]
      Warrior:    [100, 450, 800, 3000]
      Traveller:  [100, 600, 550, 2200]

  mpdoc:
    levels:       [0, 13, 25, 50]
    normalizers:  [100, 200, 300, 1500]
    costs:
      - { min: 100,     max: 500 }
      - { min: 10000,   max: 30000 }
      - { min: 200000,  max: 2000000 }
      - { min: 2000000, max: 20000000 }
    values:
      Mage:       [0, 0, 1000, 2000]
      Thief:      [0, 0, 300, 500]
      Healer:     [0, 0, 900, 1800]
      Warrior:    [0, 0, 200, 400]
      Traveller:  [0, 0, 0, 0]

  buffer:
    duration: 900
    buffs:
      - Invisibility
      - DarkVision

  axpswapper:
    level: 50

players:
  saveTicks: 150

potion:
  Lesser: 10
  Bradley: 13
  Minor: 15
  Basic: 18
  Greater: 21
  Major: 24
  Advanced: 27
  Pure: 30

skillgain:
  one: [1]
  two: [0.75, 0.25]
  three: [0.55, 0.25, 0.20]
  four: [0.45, 0.25, 0.15, 0.15]

subscriber:
  characters: 1
  smithRepair: 1000
  smithCost: 0.05
  alchemistOz: 5
  statDoc: 0.05
  succorOz: 1
  marketListings: 5
  storageSpace: 200
  axpGain: 1
  xpGain: 0.05
  skillGain: 0.05
  holidayTokenGain: 2

tradeskill:
  validTradeskills:
    - Alchemy
    - Metalworking
    - Spellforging