
character:
  maxLevel: 50
  maxSkill: 30
  maxStats: 25

subscriber:
  characters: 1
  smithRepair: 1000
  smithCost: 0.05
  alchemistOz: 5
  statDoc: 0.05
  succorOz: 1
  marketListings: 5
  storageSpace: 200
  axpGain: 1
  xpGain: 0.05
  skillGain: 0.05

event:

  # 1/3000 chance for a common event to happen randomly
  common: 3000

  uncommon: 5000

  rare: 10000

  legendary: 100000