
Chase:
  name: 'Chase'
  macro: 'chase'
  icon: 'hooded-figure'
  color: '#000000'
  mode: 'lockActivation'
  tooltipDesc: 'Move towards a target.'

Climb:
  name: 'Climb'
  macro: 'climbup'
  icon: 'ladder'
  color: '#D2691E'
  mode: 'autoActivate'
  tooltipDesc: 'Climb up or down on this tile.'

Look At:
  name: 'Look At'
  macro: 'look at'
  icon: 'look-at'
  color: '#8A6948'
  mode: 'clickToTarget'
  tooltipDesc: 'Look at a target, getting a full description of them and their gear.'

Show Skills:
  name: 'Show Skills'
  macro: 'show skills'
  icon: 'checklist'
  color: '#000000'
  mode: 'autoActivate'
  tooltipDesc: 'See all of your skills and skill levels in text form.'

Show Stats:
  name: 'Show Stats'
  macro: 'show stats'
  icon: 'checklist'
  color: '#000000'
  mode: 'autoActivate'
  tooltipDesc: 'See all of your stats and their base level in text form.'

Stairs:
  name: 'Stairs'
  macro: 'up'
  icon: '3d-stairs'
  color: '#404040'
  mode: 'autoActivate'
  tooltipDesc: 'Go up or down stairs on this tile.'

Clear Buffer:
  name: 'Clear Buffer'
  macro: '!clear'
  icon: 'ultrasound'
  color: '#000000'
  mode: 'autoActivate'
  key: 'ESCAPE'
  tooltipDesc: 'Clear the command buffer, negating all future commands.'

Drink:
  name: 'Drink'
  macro: '!drink'
  icon: 'potion-ball'
  color: '#2020B2'
  mode: 'autoActivate'
  tooltipDesc: 'Drink a potion from your potion slot.'

Look:
  name: 'Look At Ground'
  macro: '~look'
  icon: 'semi-closed-eye'
  color: '#665600'
  mode: 'autoActivate'
  tooltipDesc: 'Look at the ground without searching containers.'

Restore:
  name: 'Restore'
  macro: 'restore'
  icon: 'quicksand'
  color: '#8A6948'
  mode: 'autoActivate'
  tooltipDesc: 'Revive and go back to a respawn point.'

Search:
  name: 'Search'
  macro: '~search'
  icon: 'cash'
  color: '#665600'
  mode: 'autoActivate'
  tooltipDesc: 'Look at the ground and search containers for items.'

Attack:
  name: 'Attack'
  macro: 'attack'
  icon: 'blade-drag'
  color: '#530000'
  mode: 'lockActivation'
  tooltipDesc: 'Physically attack a target with the item in your right hand.'

Hide:
  name: 'Hide'
  macro: 'hide'
  icon: 'hidden'
  color: '#cccccc'
  bgColor: '#000000'
  mode: 'autoActivate'
  tooltipDesc: 'Hide in the shadows.'

Kick:
  name: 'Kick'
  macro: 'kick'
  icon: 'barefoot'
  color: '#530000'
  mode: 'lockActivation'
  tooltipDesc: 'Physically attack a target with your boots.'

Steal:
  name: 'Steal'
  macro: 'steal'
  icon: 'take-my-money'
  color: '#7F6B00'
  mode: 'lockActivation'
  tooltipDesc: 'Steal gold and items from your target.'

Throw:
  name: 'Throw'
  macro: 'throw right'
  icon: 'thrown-spear'
  color: '#530000'
  mode: 'lockActivation'
  tooltipDesc: 'Throw an item at a target.'